name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement   # your file is named 'requirement' not 'requirements.txt'

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -R | head -n 50

      - name: Train model
        run: python model/train.py

      - name: Run unit tests
        run: python -m unittest discover -s tests -p "test*.py" -v

      - name: Evaluate model
        run: python model/evaluate.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: churn-model
          path: model/churn_model.pkl
